[tool.poetry]
name = "fastapimemleak"
version = "0.1.0"
description = ""
authors = ["gal kahana <gal.kahana@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = {extras = ["standard"], version = "^0.18.2"}
requests = "^2.28.1"
fastapi = "^0.78.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
